#ifndef __QUAD_ENCODER_H__
#define __QUAD_ENCODER_H__

#define QUAD_ENCODER_DIR 1
#define QUAD_ENCODER_OFFSET 0x7fff
#define QUAD_ENCODER_CNT() (QUAD_ENCODER_DIR?(TIM3->CNT-QUAD_ENCODER_OFFSET):(QUAD_ENCODER_OFFSET-TIM3->CNT))
#define QUAD_ENCODER_START() (TIM3->CNT = QUAD_ENCODER_OFFSET)

void QuadEncoder_Config(void);

#endif
